IMPERAS_HOME := $(shell getpath.exe "$(IMPERAS_HOME)")

CFLAGS+= -I../../../../../ovpworld.org/modelSupport/ps2/1.0/pse
CFLAGS+= -I../../../../../ovpworld.org/modelSupport/sdlInput/1.0/model

include $(IMPERAS_HOME)/ImperasLib/buildutils/Makefile.pse
