IMPERAS_HOME := $(shell getpath.exe "$(IMPERAS_HOME)")
CFLAGS+=-I../../../../../ovpworld.org/modelSupport/VCAN/1.0/pse
CFLAGS+=-I../../../../modelSupport/can/1.0/pse

include $(IMPERAS_HOME)/ImperasLib/buildutils/Makefile.pse
