IMPERAS_HOME := $(shell getpath.exe "$(IMPERAS_HOME)")
CFLAGS+=-I../../../../../ovpworld.org/modelSupport/uart16550/1.0/pse
include $(IMPERAS_HOME)/ImperasLib/buildutils/Makefile.pse

-include Makefile.tcl
