/*
 * Copyright (c) 2005-2015 Imperas Software Ltd., www.imperas.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */


////////////////////////////////////////////////////////////////////////////////
//
//                W R I T T E N   B Y   I M P E R A S   I G E N
//
//                             Version 20150901.0
//
////////////////////////////////////////////////////////////////////////////////


#include "pse.igen.h"
/////////////////////////////// Port Declarations //////////////////////////////

bport1_ab_dataT bport1_ab_data;

handlesT handles;

/////////////////////////////// Diagnostic level ///////////////////////////////

// Test this variable to determine what diagnostics to output.
// eg. if (diagnosticLevel >= 1) bhmMessage("I", "VybridDMA", "Example");
//     Predefined macros PSE_DIAG_LOW, PSE_DIAG_MEDIUM and PSE_DIAG_HIGH may be used
Uns32 diagnosticLevel;

/////////////////////////// Diagnostic level callback //////////////////////////

static void setDiagLevel(Uns32 new) {
    diagnosticLevel = new;
}

///////////////////////////// MMR Generic callbacks ////////////////////////////

static PPM_VIEW_CB(view32) {  *(Uns32*)data = *(Uns32*)user; }

static PPM_READ_CB(read_32) {  return *(Uns32*)user; }

//////////////////////////////// Mask functions ////////////////////////////////

static PPM_WRITE_CB(bport1_ab_EARS_maskWrite) {
    bport1_ab_data.EARS.value = (bport1_ab_data.EARS.value & 0x0) | (data & 0xffffffff);
}

//////////////////////////////// Bus Slave Ports ///////////////////////////////

static void installSlavePorts(void) {
    handles.bport1 = ppmCreateSlaveBusPort("bport1", 8192);

}

//////////////////////////// Memory mapped registers ///////////////////////////

static void installRegisters(void) {

    ppmCreateRegister("ab_CR",
        "Control Register, offset: 0x0 ",
        handles.bport1,
        0,
        4,
        regReadCR,
        regWriteCR,
        view32,
        &(bport1_ab_data.CR.value),
        True
    );
    ppmCreateRegister("ab_ES",
        "Error Status Register, offset: 0x4 ",
        handles.bport1,
        4,
        4,
        regReadES,
        0,
        view32,
        &(bport1_ab_data.ES.value),
        True
    );
    ppmCreateRegister("ab_ERQ",
        "Enable Request Register, offset: 0xC ",
        handles.bport1,
        12,
        4,
        regRead32,
        regWrite32,
        view32,
        &(bport1_ab_data.ERQ.value),
        True
    );
    ppmCreateRegister("ab_EEI",
        0,
        handles.bport1,
        20,
        4,
        regRead32,
        regWrite32,
        view32,
        &(bport1_ab_data.EEI.value),
        True
    );
    ppmCreateRegister("ab_CS_EEI_ERC",
        "Clear/Set EEI, ERC",
        handles.bport1,
        24,
        4,
        regReadZero,
        regSetGroup,
        view32,
        &(bport1_ab_data.CS_EEI_ERC.value),
        True
    );
    ppmCreateRegister("ab_DNE_SRT_ERR_INT",
        "Clear/Set DNE, START, ERR, INT registers",
        handles.bport1,
        28,
        4,
        regReadZero,
        regSetGroup,
        view32,
        &(bport1_ab_data.DNE_SRT_ERR_INT.value),
        True
    );
    ppmCreateRegister("ab_INT",
        0,
        handles.bport1,
        36,
        4,
        regRead32,
        regWrite1c,
        view32,
        &(bport1_ab_data.INT.value),
        True
    );
    ppmCreateRegister("ab_ERR",
        "Error Register, offset: 0x2C ",
        handles.bport1,
        44,
        4,
        regRead32,
        regWrite1c,
        view32,
        &(bport1_ab_data.ERR.value),
        True
    );
    ppmCreateRegister("ab_HRS",
        0,
        handles.bport1,
        52,
        4,
        regRead32,
        regWrite32,
        view32,
        &(bport1_ab_data.HRS.value),
        True
    );
    ppmCreateRegister("ab_EARS",
        "Enable Asyncronous Request",
        handles.bport1,
        68,
        4,
        read_32,
        bport1_ab_EARS_maskWrite,
        view32,
        &(bport1_ab_data.EARS.value),
        True
    );
    ppmCreateRegister("ab_DCHPRI3_0",
        "Channel n Priority Registers 3 to 0",
        handles.bport1,
        256,
        4,
        regReadCHPRI,
        regWriteCHPRI,
        view32,
        &(bport1_ab_data.DCHPRI3_0.value),
        True
    );
    ppmCreateRegister("ab_DCHPRI7_4",
        0,
        handles.bport1,
        260,
        4,
        regReadCHPRI,
        regWriteCHPRI,
        view32,
        &(bport1_ab_data.DCHPRI7_4.value),
        True
    );
    ppmCreateRegister("ab_DCHPRI11_8",
        0,
        handles.bport1,
        264,
        4,
        regReadCHPRI,
        regWriteCHPRI,
        view32,
        &(bport1_ab_data.DCHPRI11_8.value),
        True
    );
    ppmCreateRegister("ab_DCHPRI15_12",
        0,
        handles.bport1,
        268,
        4,
        regReadCHPRI,
        regWriteCHPRI,
        view32,
        &(bport1_ab_data.DCHPRI15_12.value),
        True
    );
    ppmCreateRegister("ab_DCHPRI19_16",
        0,
        handles.bport1,
        272,
        4,
        regReadCHPRI,
        regWriteCHPRI,
        view32,
        &(bport1_ab_data.DCHPRI19_16.value),
        True
    );
    ppmCreateRegister("ab_DCHPRI23_20",
        0,
        handles.bport1,
        276,
        4,
        regReadCHPRI,
        regWriteCHPRI,
        view32,
        &(bport1_ab_data.DCHPRI23_20.value),
        True
    );
    ppmCreateRegister("ab_DCHPRI27_24",
        0,
        handles.bport1,
        280,
        4,
        regReadCHPRI,
        regWriteCHPRI,
        view32,
        &(bport1_ab_data.DCHPRI27_24.value),
        True
    );
    ppmCreateRegister("ab_DCHPRI31_28",
        0,
        handles.bport1,
        284,
        4,
        regReadCHPRI,
        regWriteCHPRI,
        view32,
        &(bport1_ab_data.DCHPRI31_28.value),
        True
    );
    ppmCreateRegister("ab_TCD0_SADDR",
        "TCD Source Address",
        handles.bport1,
        4096,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD0_SADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD0_SOFF_ATTR",
        "TCD Signed Source Address Offset",
        handles.bport1,
        4100,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD0_SOFF_ATTR.value),
        True
    );
    ppmCreateRegister("ab_TCD0_NBYTES",
        "TCD Signed Minor Loop Offset, Minor Loop Disabled",
        handles.bport1,
        4104,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD0_NBYTES.value),
        True
    );
    ppmCreateRegister("ab_TCD0_SLAST",
        0,
        handles.bport1,
        4108,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD0_SLAST.value),
        True
    );
    ppmCreateRegister("ab_TCD0_DADDR",
        0,
        handles.bport1,
        4112,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD0_DADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD0_DOFF_CITER",
        0,
        handles.bport1,
        4116,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD0_DOFF_CITER.value),
        True
    );
    ppmCreateRegister("ab_TCD0_DLASTSGA",
        0,
        handles.bport1,
        4120,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD0_DLASTSGA.value),
        True
    );
    ppmCreateRegister("ab_TCD0_CSR_BITER",
        0,
        handles.bport1,
        4124,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD0_CSR_BITER.value),
        True
    );
    ppmCreateRegister("ab_TCD1_SADDR",
        "TCD Source Address",
        handles.bport1,
        4128,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD1_SADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD1_SOFF_ATTR",
        "TCD Signed Source Address Offset",
        handles.bport1,
        4132,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD1_SOFF_ATTR.value),
        True
    );
    ppmCreateRegister("ab_TCD1_NBYTES",
        "TCD Signed Minor Loop Offset, Minor Loop Disabled",
        handles.bport1,
        4136,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD1_NBYTES.value),
        True
    );
    ppmCreateRegister("ab_TCD1_SLAST",
        0,
        handles.bport1,
        4140,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD1_SLAST.value),
        True
    );
    ppmCreateRegister("ab_TCD1_DADDR",
        0,
        handles.bport1,
        4144,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD1_DADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD1_DOFF_CITER",
        0,
        handles.bport1,
        4148,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD1_DOFF_CITER.value),
        True
    );
    ppmCreateRegister("ab_TCD1_DLASTSGA",
        0,
        handles.bport1,
        4152,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD1_DLASTSGA.value),
        True
    );
    ppmCreateRegister("ab_TCD1_CSR_BITER",
        0,
        handles.bport1,
        4156,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD1_CSR_BITER.value),
        True
    );
    ppmCreateRegister("ab_TCD2_SADDR",
        "TCD Source Address",
        handles.bport1,
        4160,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD2_SADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD2_SOFF_ATTR",
        "TCD Signed Source Address Offset",
        handles.bport1,
        4164,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD2_SOFF_ATTR.value),
        True
    );
    ppmCreateRegister("ab_TCD2_NBYTES",
        "TCD Signed Minor Loop Offset, Minor Loop Disabled",
        handles.bport1,
        4168,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD2_NBYTES.value),
        True
    );
    ppmCreateRegister("ab_TCD2_SLAST",
        0,
        handles.bport1,
        4172,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD2_SLAST.value),
        True
    );
    ppmCreateRegister("ab_TCD2_DADDR",
        0,
        handles.bport1,
        4176,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD2_DADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD2_DOFF_CITER",
        0,
        handles.bport1,
        4180,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD2_DOFF_CITER.value),
        True
    );
    ppmCreateRegister("ab_TCD2_DLASTSGA",
        0,
        handles.bport1,
        4184,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD2_DLASTSGA.value),
        True
    );
    ppmCreateRegister("ab_TCD2_CSR_BITER",
        0,
        handles.bport1,
        4188,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD2_CSR_BITER.value),
        True
    );
    ppmCreateRegister("ab_TCD3_SADDR",
        "TCD Source Address",
        handles.bport1,
        4192,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD3_SADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD3_SOFF_ATTR",
        "TCD Signed Source Address Offset",
        handles.bport1,
        4196,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD3_SOFF_ATTR.value),
        True
    );
    ppmCreateRegister("ab_TCD3_NBYTES",
        "TCD Signed Minor Loop Offset, Minor Loop Disabled",
        handles.bport1,
        4200,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD3_NBYTES.value),
        True
    );
    ppmCreateRegister("ab_TCD3_SLAST",
        0,
        handles.bport1,
        4204,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD3_SLAST.value),
        True
    );
    ppmCreateRegister("ab_TCD3_DADDR",
        0,
        handles.bport1,
        4208,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD3_DADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD3_DOFF_CITER",
        0,
        handles.bport1,
        4212,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD3_DOFF_CITER.value),
        True
    );
    ppmCreateRegister("ab_TCD3_DLASTSGA",
        0,
        handles.bport1,
        4216,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD3_DLASTSGA.value),
        True
    );
    ppmCreateRegister("ab_TCD3_CSR_BITER",
        0,
        handles.bport1,
        4220,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD3_CSR_BITER.value),
        True
    );
    ppmCreateRegister("ab_TCD4_SADDR",
        "TCD Source Address",
        handles.bport1,
        4224,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD4_SADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD4_SOFF_ATTR",
        "TCD Signed Source Address Offset",
        handles.bport1,
        4228,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD4_SOFF_ATTR.value),
        True
    );
    ppmCreateRegister("ab_TCD4_NBYTES",
        "TCD Signed Minor Loop Offset, Minor Loop Disabled",
        handles.bport1,
        4232,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD4_NBYTES.value),
        True
    );
    ppmCreateRegister("ab_TCD4_SLAST",
        0,
        handles.bport1,
        4236,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD4_SLAST.value),
        True
    );
    ppmCreateRegister("ab_TCD4_DADDR",
        0,
        handles.bport1,
        4240,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD4_DADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD4_DOFF_CITER",
        0,
        handles.bport1,
        4244,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD4_DOFF_CITER.value),
        True
    );
    ppmCreateRegister("ab_TCD4_DLASTSGA",
        0,
        handles.bport1,
        4248,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD4_DLASTSGA.value),
        True
    );
    ppmCreateRegister("ab_TCD4_CSR_BITER",
        0,
        handles.bport1,
        4252,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD4_CSR_BITER.value),
        True
    );
    ppmCreateRegister("ab_TCD5_SADDR",
        "TCD Source Address",
        handles.bport1,
        4256,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD5_SADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD5_SOFF_ATTR",
        "TCD Signed Source Address Offset",
        handles.bport1,
        4260,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD5_SOFF_ATTR.value),
        True
    );
    ppmCreateRegister("ab_TCD5_NBYTES",
        "TCD Signed Minor Loop Offset, Minor Loop Disabled",
        handles.bport1,
        4264,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD5_NBYTES.value),
        True
    );
    ppmCreateRegister("ab_TCD5_SLAST",
        0,
        handles.bport1,
        4268,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD5_SLAST.value),
        True
    );
    ppmCreateRegister("ab_TCD5_DADDR",
        0,
        handles.bport1,
        4272,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD5_DADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD5_DOFF_CITER",
        0,
        handles.bport1,
        4276,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD5_DOFF_CITER.value),
        True
    );
    ppmCreateRegister("ab_TCD5_DLASTSGA",
        0,
        handles.bport1,
        4280,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD5_DLASTSGA.value),
        True
    );
    ppmCreateRegister("ab_TCD5_CSR_BITER",
        0,
        handles.bport1,
        4284,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD5_CSR_BITER.value),
        True
    );
    ppmCreateRegister("ab_TCD6_SADDR",
        "TCD Source Address",
        handles.bport1,
        4288,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD6_SADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD6_SOFF_ATTR",
        "TCD Signed Source Address Offset",
        handles.bport1,
        4292,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD6_SOFF_ATTR.value),
        True
    );
    ppmCreateRegister("ab_TCD6_NBYTES",
        "TCD Signed Minor Loop Offset, Minor Loop Disabled",
        handles.bport1,
        4296,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD6_NBYTES.value),
        True
    );
    ppmCreateRegister("ab_TCD6_SLAST",
        0,
        handles.bport1,
        4300,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD6_SLAST.value),
        True
    );
    ppmCreateRegister("ab_TCD6_DADDR",
        0,
        handles.bport1,
        4304,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD6_DADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD6_DOFF_CITER",
        0,
        handles.bport1,
        4308,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD6_DOFF_CITER.value),
        True
    );
    ppmCreateRegister("ab_TCD6_DLASTSGA",
        0,
        handles.bport1,
        4312,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD6_DLASTSGA.value),
        True
    );
    ppmCreateRegister("ab_TCD6_CSR_BITER",
        0,
        handles.bport1,
        4316,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD6_CSR_BITER.value),
        True
    );
    ppmCreateRegister("ab_TCD7_SADDR",
        "TCD Source Address",
        handles.bport1,
        4320,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD7_SADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD7_SOFF_ATTR",
        "TCD Signed Source Address Offset",
        handles.bport1,
        4324,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD7_SOFF_ATTR.value),
        True
    );
    ppmCreateRegister("ab_TCD7_NBYTES",
        "TCD Signed Minor Loop Offset, Minor Loop Disabled",
        handles.bport1,
        4328,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD7_NBYTES.value),
        True
    );
    ppmCreateRegister("ab_TCD7_SLAST",
        0,
        handles.bport1,
        4332,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD7_SLAST.value),
        True
    );
    ppmCreateRegister("ab_TCD7_DADDR",
        0,
        handles.bport1,
        4336,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD7_DADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD7_DOFF_CITER",
        0,
        handles.bport1,
        4340,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD7_DOFF_CITER.value),
        True
    );
    ppmCreateRegister("ab_TCD7_DLASTSGA",
        0,
        handles.bport1,
        4344,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD7_DLASTSGA.value),
        True
    );
    ppmCreateRegister("ab_TCD7_CSR_BITER",
        0,
        handles.bport1,
        4348,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD7_CSR_BITER.value),
        True
    );
    ppmCreateRegister("ab_TCD8_SADDR",
        "TCD Source Address",
        handles.bport1,
        4352,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD8_SADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD8_SOFF_ATTR",
        "TCD Signed Source Address Offset",
        handles.bport1,
        4356,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD8_SOFF_ATTR.value),
        True
    );
    ppmCreateRegister("ab_TCD8_NBYTES",
        "TCD Signed Minor Loop Offset, Minor Loop Disabled",
        handles.bport1,
        4360,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD8_NBYTES.value),
        True
    );
    ppmCreateRegister("ab_TCD8_SLAST",
        0,
        handles.bport1,
        4364,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD8_SLAST.value),
        True
    );
    ppmCreateRegister("ab_TCD8_DADDR",
        0,
        handles.bport1,
        4368,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD8_DADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD8_DOFF_CITER",
        0,
        handles.bport1,
        4372,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD8_DOFF_CITER.value),
        True
    );
    ppmCreateRegister("ab_TCD8_DLASTSGA",
        0,
        handles.bport1,
        4376,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD8_DLASTSGA.value),
        True
    );
    ppmCreateRegister("ab_TCD8_CSR_BITER",
        0,
        handles.bport1,
        4380,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD8_CSR_BITER.value),
        True
    );
    ppmCreateRegister("ab_TCD9_SADDR",
        "TCD Source Address",
        handles.bport1,
        4384,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD9_SADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD9_SOFF_ATTR",
        "TCD Signed Source Address Offset",
        handles.bport1,
        4388,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD9_SOFF_ATTR.value),
        True
    );
    ppmCreateRegister("ab_TCD9_NBYTES",
        "TCD Signed Minor Loop Offset, Minor Loop Disabled",
        handles.bport1,
        4392,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD9_NBYTES.value),
        True
    );
    ppmCreateRegister("ab_TCD9_SLAST",
        0,
        handles.bport1,
        4396,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD9_SLAST.value),
        True
    );
    ppmCreateRegister("ab_TCD9_DADDR",
        0,
        handles.bport1,
        4400,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD9_DADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD9_DOFF_CITER",
        0,
        handles.bport1,
        4404,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD9_DOFF_CITER.value),
        True
    );
    ppmCreateRegister("ab_TCD9_DLASTSGA",
        0,
        handles.bport1,
        4408,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD9_DLASTSGA.value),
        True
    );
    ppmCreateRegister("ab_TCD9_CSR_BITER",
        0,
        handles.bport1,
        4412,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD9_CSR_BITER.value),
        True
    );
    ppmCreateRegister("ab_TCD10_SADDR",
        "TCD Source Address",
        handles.bport1,
        4416,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD10_SADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD10_SOFF_ATTR",
        "TCD Signed Source Address Offset",
        handles.bport1,
        4420,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD10_SOFF_ATTR.value),
        True
    );
    ppmCreateRegister("ab_TCD10_NBYTES",
        "TCD Signed Minor Loop Offset, Minor Loop Disabled",
        handles.bport1,
        4424,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD10_NBYTES.value),
        True
    );
    ppmCreateRegister("ab_TCD10_SLAST",
        0,
        handles.bport1,
        4428,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD10_SLAST.value),
        True
    );
    ppmCreateRegister("ab_TCD10_DADDR",
        0,
        handles.bport1,
        4432,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD10_DADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD10_DOFF_CITER",
        0,
        handles.bport1,
        4436,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD10_DOFF_CITER.value),
        True
    );
    ppmCreateRegister("ab_TCD10_DLASTSGA",
        0,
        handles.bport1,
        4440,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD10_DLASTSGA.value),
        True
    );
    ppmCreateRegister("ab_TCD10_CSR_BITER",
        0,
        handles.bport1,
        4444,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD10_CSR_BITER.value),
        True
    );
    ppmCreateRegister("ab_TCD11_SADDR",
        "TCD Source Address",
        handles.bport1,
        4448,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD11_SADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD11_SOFF_ATTR",
        "TCD Signed Source Address Offset",
        handles.bport1,
        4452,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD11_SOFF_ATTR.value),
        True
    );
    ppmCreateRegister("ab_TCD11_NBYTES",
        "TCD Signed Minor Loop Offset, Minor Loop Disabled",
        handles.bport1,
        4456,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD11_NBYTES.value),
        True
    );
    ppmCreateRegister("ab_TCD11_SLAST",
        0,
        handles.bport1,
        4460,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD11_SLAST.value),
        True
    );
    ppmCreateRegister("ab_TCD11_DADDR",
        0,
        handles.bport1,
        4464,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD11_DADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD11_DOFF_CITER",
        0,
        handles.bport1,
        4468,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD11_DOFF_CITER.value),
        True
    );
    ppmCreateRegister("ab_TCD11_DLASTSGA",
        0,
        handles.bport1,
        4472,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD11_DLASTSGA.value),
        True
    );
    ppmCreateRegister("ab_TCD11_CSR_BITER",
        0,
        handles.bport1,
        4476,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD11_CSR_BITER.value),
        True
    );
    ppmCreateRegister("ab_TCD12_SADDR",
        "TCD Source Address",
        handles.bport1,
        4480,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD12_SADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD12_SOFF_ATTR",
        "TCD Signed Source Address Offset",
        handles.bport1,
        4484,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD12_SOFF_ATTR.value),
        True
    );
    ppmCreateRegister("ab_TCD12_NBYTES",
        "TCD Signed Minor Loop Offset, Minor Loop Disabled",
        handles.bport1,
        4488,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD12_NBYTES.value),
        True
    );
    ppmCreateRegister("ab_TCD12_SLAST",
        0,
        handles.bport1,
        4492,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD12_SLAST.value),
        True
    );
    ppmCreateRegister("ab_TCD12_DADDR",
        0,
        handles.bport1,
        4496,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD12_DADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD12_DOFF_CITER",
        0,
        handles.bport1,
        4500,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD12_DOFF_CITER.value),
        True
    );
    ppmCreateRegister("ab_TCD12_DLASTSGA",
        0,
        handles.bport1,
        4504,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD12_DLASTSGA.value),
        True
    );
    ppmCreateRegister("ab_TCD12_CSR_BITER",
        0,
        handles.bport1,
        4508,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD12_CSR_BITER.value),
        True
    );
    ppmCreateRegister("ab_TCD13_SADDR",
        "TCD Source Address",
        handles.bport1,
        4512,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD13_SADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD13_SOFF_ATTR",
        "TCD Signed Source Address Offset",
        handles.bport1,
        4516,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD13_SOFF_ATTR.value),
        True
    );
    ppmCreateRegister("ab_TCD13_NBYTES",
        "TCD Signed Minor Loop Offset, Minor Loop Disabled",
        handles.bport1,
        4520,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD13_NBYTES.value),
        True
    );
    ppmCreateRegister("ab_TCD13_SLAST",
        0,
        handles.bport1,
        4524,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD13_SLAST.value),
        True
    );
    ppmCreateRegister("ab_TCD13_DADDR",
        0,
        handles.bport1,
        4528,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD13_DADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD13_DOFF_CITER",
        0,
        handles.bport1,
        4532,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD13_DOFF_CITER.value),
        True
    );
    ppmCreateRegister("ab_TCD13_DLASTSGA",
        0,
        handles.bport1,
        4536,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD13_DLASTSGA.value),
        True
    );
    ppmCreateRegister("ab_TCD13_CSR_BITER",
        0,
        handles.bport1,
        4540,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD13_CSR_BITER.value),
        True
    );
    ppmCreateRegister("ab_TCD14_SADDR",
        "TCD Source Address",
        handles.bport1,
        4544,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD14_SADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD14_SOFF_ATTR",
        "TCD Signed Source Address Offset",
        handles.bport1,
        4548,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD14_SOFF_ATTR.value),
        True
    );
    ppmCreateRegister("ab_TCD14_NBYTES",
        "TCD Signed Minor Loop Offset, Minor Loop Disabled",
        handles.bport1,
        4552,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD14_NBYTES.value),
        True
    );
    ppmCreateRegister("ab_TCD14_SLAST",
        0,
        handles.bport1,
        4556,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD14_SLAST.value),
        True
    );
    ppmCreateRegister("ab_TCD14_DADDR",
        0,
        handles.bport1,
        4560,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD14_DADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD14_DOFF_CITER",
        0,
        handles.bport1,
        4564,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD14_DOFF_CITER.value),
        True
    );
    ppmCreateRegister("ab_TCD14_DLASTSGA",
        0,
        handles.bport1,
        4568,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD14_DLASTSGA.value),
        True
    );
    ppmCreateRegister("ab_TCD14_CSR_BITER",
        0,
        handles.bport1,
        4572,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD14_CSR_BITER.value),
        True
    );
    ppmCreateRegister("ab_TCD15_SADDR",
        "TCD Source Address",
        handles.bport1,
        4576,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD15_SADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD15_SOFF_ATTR",
        "TCD Signed Source Address Offset",
        handles.bport1,
        4580,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD15_SOFF_ATTR.value),
        True
    );
    ppmCreateRegister("ab_TCD15_NBYTES",
        "TCD Signed Minor Loop Offset, Minor Loop Disabled",
        handles.bport1,
        4584,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD15_NBYTES.value),
        True
    );
    ppmCreateRegister("ab_TCD15_SLAST",
        0,
        handles.bport1,
        4588,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD15_SLAST.value),
        True
    );
    ppmCreateRegister("ab_TCD15_DADDR",
        0,
        handles.bport1,
        4592,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD15_DADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD15_DOFF_CITER",
        0,
        handles.bport1,
        4596,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD15_DOFF_CITER.value),
        True
    );
    ppmCreateRegister("ab_TCD15_DLASTSGA",
        0,
        handles.bport1,
        4600,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD15_DLASTSGA.value),
        True
    );
    ppmCreateRegister("ab_TCD15_CSR_BITER",
        0,
        handles.bport1,
        4604,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD15_CSR_BITER.value),
        True
    );
    ppmCreateRegister("ab_TCD16_SADDR",
        "TCD Source Address",
        handles.bport1,
        4608,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD16_SADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD16_SOFF_ATTR",
        "TCD Signed Source Address Offset",
        handles.bport1,
        4612,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD16_SOFF_ATTR.value),
        True
    );
    ppmCreateRegister("ab_TCD16_NBYTES",
        "TCD Signed Minor Loop Offset, Minor Loop Disabled",
        handles.bport1,
        4616,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD16_NBYTES.value),
        True
    );
    ppmCreateRegister("ab_TCD16_SLAST",
        0,
        handles.bport1,
        4620,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD16_SLAST.value),
        True
    );
    ppmCreateRegister("ab_TCD16_DADDR",
        0,
        handles.bport1,
        4624,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD16_DADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD16_DOFF_CITER",
        0,
        handles.bport1,
        4628,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD16_DOFF_CITER.value),
        True
    );
    ppmCreateRegister("ab_TCD16_DLASTSGA",
        0,
        handles.bport1,
        4632,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD16_DLASTSGA.value),
        True
    );
    ppmCreateRegister("ab_TCD16_CSR_BITER",
        0,
        handles.bport1,
        4636,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD16_CSR_BITER.value),
        True
    );
    ppmCreateRegister("ab_TCD17_SADDR",
        "TCD Source Address",
        handles.bport1,
        4640,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD17_SADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD17_SOFF_ATTR",
        "TCD Signed Source Address Offset",
        handles.bport1,
        4644,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD17_SOFF_ATTR.value),
        True
    );
    ppmCreateRegister("ab_TCD17_NBYTES",
        "TCD Signed Minor Loop Offset, Minor Loop Disabled",
        handles.bport1,
        4648,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD17_NBYTES.value),
        True
    );
    ppmCreateRegister("ab_TCD17_SLAST",
        0,
        handles.bport1,
        4652,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD17_SLAST.value),
        True
    );
    ppmCreateRegister("ab_TCD17_DADDR",
        0,
        handles.bport1,
        4656,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD17_DADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD17_DOFF_CITER",
        0,
        handles.bport1,
        4660,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD17_DOFF_CITER.value),
        True
    );
    ppmCreateRegister("ab_TCD17_DLASTSGA",
        0,
        handles.bport1,
        4664,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD17_DLASTSGA.value),
        True
    );
    ppmCreateRegister("ab_TCD17_CSR_BITER",
        0,
        handles.bport1,
        4668,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD17_CSR_BITER.value),
        True
    );
    ppmCreateRegister("ab_TCD18_SADDR",
        "TCD Source Address",
        handles.bport1,
        4672,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD18_SADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD18_SOFF_ATTR",
        "TCD Signed Source Address Offset",
        handles.bport1,
        4676,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD18_SOFF_ATTR.value),
        True
    );
    ppmCreateRegister("ab_TCD18_NBYTES",
        "TCD Signed Minor Loop Offset, Minor Loop Disabled",
        handles.bport1,
        4680,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD18_NBYTES.value),
        True
    );
    ppmCreateRegister("ab_TCD18_SLAST",
        0,
        handles.bport1,
        4684,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD18_SLAST.value),
        True
    );
    ppmCreateRegister("ab_TCD18_DADDR",
        0,
        handles.bport1,
        4688,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD18_DADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD18_DOFF_CITER",
        0,
        handles.bport1,
        4692,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD18_DOFF_CITER.value),
        True
    );
    ppmCreateRegister("ab_TCD18_DLASTSGA",
        0,
        handles.bport1,
        4696,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD18_DLASTSGA.value),
        True
    );
    ppmCreateRegister("ab_TCD18_CSR_BITER",
        0,
        handles.bport1,
        4700,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD18_CSR_BITER.value),
        True
    );
    ppmCreateRegister("ab_TCD19_SADDR",
        "TCD Source Address",
        handles.bport1,
        4704,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD19_SADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD19_SOFF_ATTR",
        "TCD Signed Source Address Offset",
        handles.bport1,
        4708,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD19_SOFF_ATTR.value),
        True
    );
    ppmCreateRegister("ab_TCD19_NBYTES",
        "TCD Signed Minor Loop Offset, Minor Loop Disabled",
        handles.bport1,
        4712,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD19_NBYTES.value),
        True
    );
    ppmCreateRegister("ab_TCD19_SLAST",
        0,
        handles.bport1,
        4716,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD19_SLAST.value),
        True
    );
    ppmCreateRegister("ab_TCD19_DADDR",
        0,
        handles.bport1,
        4720,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD19_DADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD19_DOFF_CITER",
        0,
        handles.bport1,
        4724,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD19_DOFF_CITER.value),
        True
    );
    ppmCreateRegister("ab_TCD19_DLASTSGA",
        0,
        handles.bport1,
        4728,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD19_DLASTSGA.value),
        True
    );
    ppmCreateRegister("ab_TCD19_CSR_BITER",
        0,
        handles.bport1,
        4732,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD19_CSR_BITER.value),
        True
    );
    ppmCreateRegister("ab_TCD20_SADDR",
        "TCD Source Address",
        handles.bport1,
        4736,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD20_SADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD20_SOFF_ATTR",
        "TCD Signed Source Address Offset",
        handles.bport1,
        4740,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD20_SOFF_ATTR.value),
        True
    );
    ppmCreateRegister("ab_TCD20_NBYTES",
        "TCD Signed Minor Loop Offset, Minor Loop Disabled",
        handles.bport1,
        4744,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD20_NBYTES.value),
        True
    );
    ppmCreateRegister("ab_TCD20_SLAST",
        0,
        handles.bport1,
        4748,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD20_SLAST.value),
        True
    );
    ppmCreateRegister("ab_TCD20_DADDR",
        0,
        handles.bport1,
        4752,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD20_DADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD20_DOFF_CITER",
        0,
        handles.bport1,
        4756,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD20_DOFF_CITER.value),
        True
    );
    ppmCreateRegister("ab_TCD20_DLASTSGA",
        0,
        handles.bport1,
        4760,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD20_DLASTSGA.value),
        True
    );
    ppmCreateRegister("ab_TCD20_CSR_BITER",
        0,
        handles.bport1,
        4764,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD20_CSR_BITER.value),
        True
    );
    ppmCreateRegister("ab_TCD21_SADDR",
        "TCD Source Address",
        handles.bport1,
        4768,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD21_SADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD21_SOFF_ATTR",
        "TCD Signed Source Address Offset",
        handles.bport1,
        4772,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD21_SOFF_ATTR.value),
        True
    );
    ppmCreateRegister("ab_TCD21_NBYTES",
        "TCD Signed Minor Loop Offset, Minor Loop Disabled",
        handles.bport1,
        4776,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD21_NBYTES.value),
        True
    );
    ppmCreateRegister("ab_TCD21_SLAST",
        0,
        handles.bport1,
        4780,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD21_SLAST.value),
        True
    );
    ppmCreateRegister("ab_TCD21_DADDR",
        0,
        handles.bport1,
        4784,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD21_DADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD21_DOFF_CITER",
        0,
        handles.bport1,
        4788,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD21_DOFF_CITER.value),
        True
    );
    ppmCreateRegister("ab_TCD21_DLASTSGA",
        0,
        handles.bport1,
        4792,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD21_DLASTSGA.value),
        True
    );
    ppmCreateRegister("ab_TCD21_CSR_BITER",
        0,
        handles.bport1,
        4796,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD21_CSR_BITER.value),
        True
    );
    ppmCreateRegister("ab_TCD22_SADDR",
        "TCD Source Address",
        handles.bport1,
        4800,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD22_SADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD22_SOFF_ATTR",
        "TCD Signed Source Address Offset",
        handles.bport1,
        4804,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD22_SOFF_ATTR.value),
        True
    );
    ppmCreateRegister("ab_TCD22_NBYTES",
        "TCD Signed Minor Loop Offset, Minor Loop Disabled",
        handles.bport1,
        4808,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD22_NBYTES.value),
        True
    );
    ppmCreateRegister("ab_TCD22_SLAST",
        0,
        handles.bport1,
        4812,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD22_SLAST.value),
        True
    );
    ppmCreateRegister("ab_TCD22_DADDR",
        0,
        handles.bport1,
        4816,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD22_DADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD22_DOFF_CITER",
        0,
        handles.bport1,
        4820,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD22_DOFF_CITER.value),
        True
    );
    ppmCreateRegister("ab_TCD22_DLASTSGA",
        0,
        handles.bport1,
        4824,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD22_DLASTSGA.value),
        True
    );
    ppmCreateRegister("ab_TCD22_CSR_BITER",
        0,
        handles.bport1,
        4828,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD22_CSR_BITER.value),
        True
    );
    ppmCreateRegister("ab_TCD23_SADDR",
        "TCD Source Address",
        handles.bport1,
        4832,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD23_SADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD23_SOFF_ATTR",
        "TCD Signed Source Address Offset",
        handles.bport1,
        4836,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD23_SOFF_ATTR.value),
        True
    );
    ppmCreateRegister("ab_TCD23_NBYTES",
        "TCD Signed Minor Loop Offset, Minor Loop Disabled",
        handles.bport1,
        4840,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD23_NBYTES.value),
        True
    );
    ppmCreateRegister("ab_TCD23_SLAST",
        0,
        handles.bport1,
        4844,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD23_SLAST.value),
        True
    );
    ppmCreateRegister("ab_TCD23_DADDR",
        0,
        handles.bport1,
        4848,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD23_DADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD23_DOFF_CITER",
        0,
        handles.bport1,
        4852,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD23_DOFF_CITER.value),
        True
    );
    ppmCreateRegister("ab_TCD23_DLASTSGA",
        0,
        handles.bport1,
        4856,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD23_DLASTSGA.value),
        True
    );
    ppmCreateRegister("ab_TCD23_CSR_BITER",
        0,
        handles.bport1,
        4860,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD23_CSR_BITER.value),
        True
    );
    ppmCreateRegister("ab_TCD24_SADDR",
        "TCD Source Address",
        handles.bport1,
        4864,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD24_SADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD24_SOFF_ATTR",
        "TCD Signed Source Address Offset",
        handles.bport1,
        4868,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD24_SOFF_ATTR.value),
        True
    );
    ppmCreateRegister("ab_TCD24_NBYTES",
        "TCD Signed Minor Loop Offset, Minor Loop Disabled",
        handles.bport1,
        4872,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD24_NBYTES.value),
        True
    );
    ppmCreateRegister("ab_TCD24_SLAST",
        0,
        handles.bport1,
        4876,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD24_SLAST.value),
        True
    );
    ppmCreateRegister("ab_TCD24_DADDR",
        0,
        handles.bport1,
        4880,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD24_DADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD24_DOFF_CITER",
        0,
        handles.bport1,
        4884,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD24_DOFF_CITER.value),
        True
    );
    ppmCreateRegister("ab_TCD24_DLASTSGA",
        0,
        handles.bport1,
        4888,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD24_DLASTSGA.value),
        True
    );
    ppmCreateRegister("ab_TCD24_CSR_BITER",
        0,
        handles.bport1,
        4892,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD24_CSR_BITER.value),
        True
    );
    ppmCreateRegister("ab_TCD25_SADDR",
        "TCD Source Address",
        handles.bport1,
        4896,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD25_SADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD25_SOFF_ATTR",
        "TCD Signed Source Address Offset",
        handles.bport1,
        4900,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD25_SOFF_ATTR.value),
        True
    );
    ppmCreateRegister("ab_TCD25_NBYTES",
        "TCD Signed Minor Loop Offset, Minor Loop Disabled",
        handles.bport1,
        4904,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD25_NBYTES.value),
        True
    );
    ppmCreateRegister("ab_TCD25_SLAST",
        0,
        handles.bport1,
        4908,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD25_SLAST.value),
        True
    );
    ppmCreateRegister("ab_TCD25_DADDR",
        0,
        handles.bport1,
        4912,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD25_DADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD25_DOFF_CITER",
        0,
        handles.bport1,
        4916,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD25_DOFF_CITER.value),
        True
    );
    ppmCreateRegister("ab_TCD25_DLASTSGA",
        0,
        handles.bport1,
        4920,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD25_DLASTSGA.value),
        True
    );
    ppmCreateRegister("ab_TCD25_CSR_BITER",
        0,
        handles.bport1,
        4924,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD25_CSR_BITER.value),
        True
    );
    ppmCreateRegister("ab_TCD26_SADDR",
        "TCD Source Address",
        handles.bport1,
        4928,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD26_SADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD26_SOFF_ATTR",
        "TCD Signed Source Address Offset",
        handles.bport1,
        4932,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD26_SOFF_ATTR.value),
        True
    );
    ppmCreateRegister("ab_TCD26_NBYTES",
        "TCD Signed Minor Loop Offset, Minor Loop Disabled",
        handles.bport1,
        4936,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD26_NBYTES.value),
        True
    );
    ppmCreateRegister("ab_TCD26_SLAST",
        0,
        handles.bport1,
        4940,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD26_SLAST.value),
        True
    );
    ppmCreateRegister("ab_TCD26_DADDR",
        0,
        handles.bport1,
        4944,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD26_DADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD26_DOFF_CITER",
        0,
        handles.bport1,
        4948,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD26_DOFF_CITER.value),
        True
    );
    ppmCreateRegister("ab_TCD26_DLASTSGA",
        0,
        handles.bport1,
        4952,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD26_DLASTSGA.value),
        True
    );
    ppmCreateRegister("ab_TCD26_CSR_BITER",
        0,
        handles.bport1,
        4956,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD26_CSR_BITER.value),
        True
    );
    ppmCreateRegister("ab_TCD27_SADDR",
        "TCD Source Address",
        handles.bport1,
        4960,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD27_SADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD27_SOFF_ATTR",
        "TCD Signed Source Address Offset",
        handles.bport1,
        4964,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD27_SOFF_ATTR.value),
        True
    );
    ppmCreateRegister("ab_TCD27_NBYTES",
        "TCD Signed Minor Loop Offset, Minor Loop Disabled",
        handles.bport1,
        4968,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD27_NBYTES.value),
        True
    );
    ppmCreateRegister("ab_TCD27_SLAST",
        0,
        handles.bport1,
        4972,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD27_SLAST.value),
        True
    );
    ppmCreateRegister("ab_TCD27_DADDR",
        0,
        handles.bport1,
        4976,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD27_DADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD27_DOFF_CITER",
        0,
        handles.bport1,
        4980,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD27_DOFF_CITER.value),
        True
    );
    ppmCreateRegister("ab_TCD27_DLASTSGA",
        0,
        handles.bport1,
        4984,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD27_DLASTSGA.value),
        True
    );
    ppmCreateRegister("ab_TCD27_CSR_BITER",
        0,
        handles.bport1,
        4988,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD27_CSR_BITER.value),
        True
    );
    ppmCreateRegister("ab_TCD28_SADDR",
        "TCD Source Address",
        handles.bport1,
        4992,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD28_SADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD28_SOFF_ATTR",
        "TCD Signed Source Address Offset",
        handles.bport1,
        4996,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD28_SOFF_ATTR.value),
        True
    );
    ppmCreateRegister("ab_TCD28_NBYTES",
        "TCD Signed Minor Loop Offset, Minor Loop Disabled",
        handles.bport1,
        5000,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD28_NBYTES.value),
        True
    );
    ppmCreateRegister("ab_TCD28_SLAST",
        0,
        handles.bport1,
        5004,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD28_SLAST.value),
        True
    );
    ppmCreateRegister("ab_TCD28_DADDR",
        0,
        handles.bport1,
        5008,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD28_DADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD28_DOFF_CITER",
        0,
        handles.bport1,
        5012,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD28_DOFF_CITER.value),
        True
    );
    ppmCreateRegister("ab_TCD28_DLASTSGA",
        0,
        handles.bport1,
        5016,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD28_DLASTSGA.value),
        True
    );
    ppmCreateRegister("ab_TCD28_CSR_BITER",
        0,
        handles.bport1,
        5020,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD28_CSR_BITER.value),
        True
    );
    ppmCreateRegister("ab_TCD29_SADDR",
        "TCD Source Address",
        handles.bport1,
        5024,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD29_SADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD29_SOFF_ATTR",
        "TCD Signed Source Address Offset",
        handles.bport1,
        5028,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD29_SOFF_ATTR.value),
        True
    );
    ppmCreateRegister("ab_TCD29_NBYTES",
        "TCD Signed Minor Loop Offset, Minor Loop Disabled",
        handles.bport1,
        5032,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD29_NBYTES.value),
        True
    );
    ppmCreateRegister("ab_TCD29_SLAST",
        0,
        handles.bport1,
        5036,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD29_SLAST.value),
        True
    );
    ppmCreateRegister("ab_TCD29_DADDR",
        0,
        handles.bport1,
        5040,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD29_DADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD29_DOFF_CITER",
        0,
        handles.bport1,
        5044,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD29_DOFF_CITER.value),
        True
    );
    ppmCreateRegister("ab_TCD29_DLASTSGA",
        0,
        handles.bport1,
        5048,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD29_DLASTSGA.value),
        True
    );
    ppmCreateRegister("ab_TCD29_CSR_BITER",
        0,
        handles.bport1,
        5052,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD29_CSR_BITER.value),
        True
    );
    ppmCreateRegister("ab_TCD30_SADDR",
        "TCD Source Address",
        handles.bport1,
        5056,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD30_SADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD30_SOFF_ATTR",
        "TCD Signed Source Address Offset",
        handles.bport1,
        5060,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD30_SOFF_ATTR.value),
        True
    );
    ppmCreateRegister("ab_TCD30_NBYTES",
        "TCD Signed Minor Loop Offset, Minor Loop Disabled",
        handles.bport1,
        5064,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD30_NBYTES.value),
        True
    );
    ppmCreateRegister("ab_TCD30_SLAST",
        0,
        handles.bport1,
        5068,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD30_SLAST.value),
        True
    );
    ppmCreateRegister("ab_TCD30_DADDR",
        0,
        handles.bport1,
        5072,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD30_DADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD30_DOFF_CITER",
        0,
        handles.bport1,
        5076,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD30_DOFF_CITER.value),
        True
    );
    ppmCreateRegister("ab_TCD30_DLASTSGA",
        0,
        handles.bport1,
        5080,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD30_DLASTSGA.value),
        True
    );
    ppmCreateRegister("ab_TCD30_CSR_BITER",
        0,
        handles.bport1,
        5084,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD30_CSR_BITER.value),
        True
    );
    ppmCreateRegister("ab_TCD31_SADDR",
        "TCD Source Address",
        handles.bport1,
        5088,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD31_SADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD31_SOFF_ATTR",
        "TCD Signed Source Address Offset",
        handles.bport1,
        5092,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD31_SOFF_ATTR.value),
        True
    );
    ppmCreateRegister("ab_TCD31_NBYTES",
        "TCD Signed Minor Loop Offset, Minor Loop Disabled",
        handles.bport1,
        5096,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD31_NBYTES.value),
        True
    );
    ppmCreateRegister("ab_TCD31_SLAST",
        0,
        handles.bport1,
        5100,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD31_SLAST.value),
        True
    );
    ppmCreateRegister("ab_TCD31_DADDR",
        0,
        handles.bport1,
        5104,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD31_DADDR.value),
        True
    );
    ppmCreateRegister("ab_TCD31_DOFF_CITER",
        0,
        handles.bport1,
        5108,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD31_DOFF_CITER.value),
        True
    );
    ppmCreateRegister("ab_TCD31_DLASTSGA",
        0,
        handles.bport1,
        5112,
        4,
        regReadTCD,
        regWriteTCD,
        view32,
        &(bport1_ab_data.TCD31_DLASTSGA.value),
        True
    );
    ppmCreateRegister("ab_TCD31_CSR_BITER",
        0,
        handles.bport1,
        5116,
        4,
        regReadTCD16,
        regWriteTCD16,
        view32,
        &(bport1_ab_data.TCD31_CSR_BITER.value),
        True
    );

}

/////////////////////////////// Bus Master Ports ///////////////////////////////

static void installMasterPorts(void) {
    handles.MREAD = ppmOpenAddressSpace("MREAD");
    handles.MWRITE = ppmOpenAddressSpace("MWRITE");
}

/////////////////////////////////// Net Ports //////////////////////////////////

static void installNetPorts(void) {
    handles.Reset = ppmOpenNetPort("Reset");
    if (handles.Reset) {
        ppmInstallNetCallback(handles.Reset, DMAReset, (void*)0);
    }

    handles.eDMARequest = ppmOpenNetPort("eDMARequest");
    if (handles.eDMARequest) {
        ppmInstallNetCallback(handles.eDMARequest, DMARequest, (void*)0);
    }

// To write to this net, use ppmWriteNet(handles.eDMADone, value);

    handles.eDMADone = ppmOpenNetPort("eDMADone");

// To write to this net, use ppmWriteNet(handles.errorInterrupt, value);

    handles.errorInterrupt = ppmOpenNetPort("errorInterrupt");

// To write to this net, use ppmWriteNet(handles.dmaInterrupt_ch0, value);

    handles.dmaInterrupt_ch0 = ppmOpenNetPort("dmaInterrupt_ch0");

// To write to this net, use ppmWriteNet(handles.dmaInterrupt_ch1, value);

    handles.dmaInterrupt_ch1 = ppmOpenNetPort("dmaInterrupt_ch1");

// To write to this net, use ppmWriteNet(handles.dmaInterrupt_ch2, value);

    handles.dmaInterrupt_ch2 = ppmOpenNetPort("dmaInterrupt_ch2");

// To write to this net, use ppmWriteNet(handles.dmaInterrupt_ch3, value);

    handles.dmaInterrupt_ch3 = ppmOpenNetPort("dmaInterrupt_ch3");

// To write to this net, use ppmWriteNet(handles.dmaInterrupt_ch4, value);

    handles.dmaInterrupt_ch4 = ppmOpenNetPort("dmaInterrupt_ch4");

// To write to this net, use ppmWriteNet(handles.dmaInterrupt_ch5, value);

    handles.dmaInterrupt_ch5 = ppmOpenNetPort("dmaInterrupt_ch5");

// To write to this net, use ppmWriteNet(handles.dmaInterrupt_ch6, value);

    handles.dmaInterrupt_ch6 = ppmOpenNetPort("dmaInterrupt_ch6");

// To write to this net, use ppmWriteNet(handles.dmaInterrupt_ch7, value);

    handles.dmaInterrupt_ch7 = ppmOpenNetPort("dmaInterrupt_ch7");

// To write to this net, use ppmWriteNet(handles.dmaInterrupt_ch8, value);

    handles.dmaInterrupt_ch8 = ppmOpenNetPort("dmaInterrupt_ch8");

// To write to this net, use ppmWriteNet(handles.dmaInterrupt_ch9, value);

    handles.dmaInterrupt_ch9 = ppmOpenNetPort("dmaInterrupt_ch9");

// To write to this net, use ppmWriteNet(handles.dmaInterrupt_ch10, value);

    handles.dmaInterrupt_ch10 = ppmOpenNetPort("dmaInterrupt_ch10");

// To write to this net, use ppmWriteNet(handles.dmaInterrupt_ch11, value);

    handles.dmaInterrupt_ch11 = ppmOpenNetPort("dmaInterrupt_ch11");

// To write to this net, use ppmWriteNet(handles.dmaInterrupt_ch12, value);

    handles.dmaInterrupt_ch12 = ppmOpenNetPort("dmaInterrupt_ch12");

// To write to this net, use ppmWriteNet(handles.dmaInterrupt_ch13, value);

    handles.dmaInterrupt_ch13 = ppmOpenNetPort("dmaInterrupt_ch13");

// To write to this net, use ppmWriteNet(handles.dmaInterrupt_ch14, value);

    handles.dmaInterrupt_ch14 = ppmOpenNetPort("dmaInterrupt_ch14");

// To write to this net, use ppmWriteNet(handles.dmaInterrupt_ch15, value);

    handles.dmaInterrupt_ch15 = ppmOpenNetPort("dmaInterrupt_ch15");

}

PPM_NET_CB(reset_Reset) {
    if(value != 0 ) {
        bport1_ab_data.EARS.value = 0x0;
        bport1_ab_data.HRS.value = 0x0;
        bport1_ab_data.ERR.value = 0x0;
        bport1_ab_data.INT.value = 0x0;
        bport1_ab_data.EEI.value = 0x0;
        bport1_ab_data.ERQ.value = 0x0;
        bport1_ab_data.ES.value = 0x0;
        bport1_ab_data.CR.value = 0x400;
    }
}

////////////////////////////////// Constructor /////////////////////////////////

PPM_CONSTRUCTOR_CB(periphConstructor) {
    installSlavePorts();
    installRegisters();
    installMasterPorts();
    installNetPorts();
    reset_Reset(1,0);
}

///////////////////////////////////// Main /////////////////////////////////////

int main(int argc, char *argv[]) {

    ppmDocNodeP Root1_node = ppmDocAddSection(0, "Root");
    {
        ppmDocNodeP doc2_node = ppmDocAddSection(Root1_node, "Description");
        ppmDocAddText(doc2_node, "Freescale Vybrid Direct Memory Access Controller");
        ppmDocNodeP doc_12_node = ppmDocAddSection(Root1_node, "Limitations");
        ppmDocAddText(doc_12_node, "Only models control register read/write - control register CX and ECX bits are modeled as RAZ/WI");
        ppmDocNodeP doc_22_node = ppmDocAddSection(Root1_node, "Licensing");
        ppmDocAddText(doc_22_node, "Open Source Apache 2.0");
        ppmDocNodeP doc_32_node = ppmDocAddSection(Root1_node, "Reference");
        ppmDocAddText(doc_32_node, "Freescale Vybrid Peripheral User Guide");
    }

    diagnosticLevel = 0;
    bhmInstallDiagCB(setDiagLevel);
    constructor();

    bhmWaitEvent(bhmGetSystemEvent(BHM_SE_END_OF_SIMULATION));
    return 0;
}

