IMPERAS_HOME := $(shell getpath.exe "$(IMPERAS_HOME)")
CFLAGS=-I../../../../..
CFLAGS+=-I../../../../../power.ovpworld.org/processor/powerpc32/1.0/model
include $(IMPERAS_HOME)/ImperasLib/buildutils/Makefile.host
